#配置数据库连接信息
spring:
  datasource:
        url: jdbc:mysql://localhost:3306/Tilas
        username: root
        password: '031107'
        driver-class-name: com.mysql.jdbc.Driver
  application:
    name: Tilas
  servlet:
    multipart:
      #修改文件上传大小限制
      max-file-size: 10MB #默认是1MB
      max-request-size: 100MB #默认是10MB

#配置mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #驼峰命名映射开关
    map-underscore-to-camel-case: true

#配置事务管理日志级别
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug

